export const siteConfig = {
  name: 'Farouk Adedamola',
  title: 'Farouk Adedamola - Software Engineer & Software Developer',
  description:
    'Software Engineer with 4+ years of experience building scalable web applications using React, Next.js, TypeScript, and modern web technologies. Specialized in performance optimization, clean architecture, and delivering exceptional user experiences.',
  url: process.env.SITE_URL || 'https://farouk.dev',
  ogImage: '/og-image.jpg',
  keywords: [
    'Farouk Adedamola',
    'Frontend Engineer',
    'Software Developer',
    'senior software engineer',
    'software engineer',
    'software developer',
    'software engineer with 4+ years of experience',
    'software developer with 4+ years of experience',
    'software engineer with 4+ years of experience building scalable web applications',
    'software developer with 4+ years of experience building scalable web applications',
    'software engineer with 4+ years of experience building scalable web applications using React, Next.js, TypeScript, and modern web technologies',
    'software developer with 4+ years of experience building scalable web applications using React, Next.js, TypeScript, and modern web technologies',
    'React Developer',
    'Next.js Developer',
    'TypeScript Developer',
    'Web Developer',
    'JavaScript Engineer',
    'UI Engineer',
    'Full Stack Developer',
    'GraphQL Developer',
    'Remote Software Engineer',
    'Frontend Consultant',
    'Web Application Developer',
    'Performance Optimization',
    'Clean Architecture',
    'Software Engineering',
    'Portfolio',
  ],
  author: {
    name: 'Farouk Adedamola',
    email: 'eja.farouk.dev@gmail.com',
    twitter: '@Farouk_fish',
    github: 'https://github.com/Farouk-Adedamola',
    linkedin: 'https://www.linkedin.com/in/farouk-adedamola/',
  },
  links: {
    twitter: 'https://x.com/Farouk_fish',
    github: 'https://github.com/Farouk-Adedamola',
    linkedin: 'https://www.linkedin.com/in/farouk-adedamola/',
  },
};

export const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: siteConfig.name,
  url: siteConfig.url,
  image: `${siteConfig.url}${siteConfig.ogImage}`,
  sameAs: [
    siteConfig.links.twitter,
    siteConfig.links.github,
    siteConfig.links.linkedin,
  ],
  jobTitle: 'Software Engineer',
  worksFor: {
    '@type': 'Organization',
    name: 'Serve Consulting',
  },
  knowsAbout: [
    'React',
    'Next.js',
    'TypeScript',
    'JavaScript',
    'GraphQL',
    'Node.js',
    'Web Development',
    'Software Engineering',
    'Frontend Development',
    'UI Engineering',
  ],
  description: siteConfig.description,
};

